spring:
  profiles:
    active: dev
server:
  port: 8080
mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml
    - classpath:dao/**/*.xml
    - classpath*:dao/**/*.xml
    - classpath*:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  configuration:
#    #开启驼峰uName自动映射到u_name
#    map-underscore-to-camel-case: true

# 打印sql
logging:
  level:
    ssm.app.mapper : debug

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: hotel-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头


secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload
      - /mail/sentMailVerificationCode
      - /**

aliyun:
  oss:
    #    endpoint: oss-cn-shenzhen.aliyuncs.com # oss对外服务的访问域名
    #    accessKeyId: test # 访问身份验证中用到用户标识
    #    accessKeySecret: test # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    #    bucketName: macro-oss # oss的存储空间
    endpoint: oss-cn-shenzhen.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI4FcNiWzTnidZsPD8bCNh # 访问身份验证中用到用户标识
    accessKeySecret: FSPnXdqGNMUrPOLHkXgwtj3xXnYBMu # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: macro-oss444 # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://39.98.190.128:8080/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: mall/images/ # 上传文件夹路径前缀

minio:
  endpoint: http://127.0.0.1:9000 #MinIO服务所在地址
  bucketName: hotel #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
